import Head from 'next/head'
import InputBox from '../components/InputBox';

export default function Home() {
  return (
    <div>
      <Head>
        <title>SoccerDB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Lets make something</h1>
      <InputBox />

    </div>
  )
}
